version: '3.3'

services:
  db:
    image: mysql:5.6
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: database
      MYSQL_USER: database_user
      MYSQL_PASSWORD: 12345678
    volumes:
      - projectsqldata:/var/lib/mysql
  php:
    build: ./docker/php
    links:
      - db
    ports:
      - "9000:9000"
    environment:
      APPLICATION_ENV: development
      ENABLE_XDEBUG: 1
      PHP_XDEBUG: 1
      PHP_XDEBUG_DEFAULT_ENABLE: 1
      PHP_XDEBUG_REMOTE_CONNECT_BACK: 0
      PHP_XDEBUG_REMOTE_PORT: 9999
      PHP_XDEBUG_REMOTE_HOST: 172.17.0.1
      PHP_XDEBUG_IDEKEY: PHPSTORM
      PHP_XDEBUG_REMOTE_LOG: /tmp/xdebug.log
      XDEBUG_CONFIG: "remote_host=YOUR_HOST"
      PHP_IDE_CONFIG: "serverName=MyProject"
      APP_DEBUG: 1
      APP_ENV: "dev"
    volumes:
      - ./project:/var/www/html

  mailhog:
    image: mailhog/mailhog
    restart: always
    ports:
      - 1025:1025
      - 8025:8025

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./project:/var/www/html
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./var/log/nginx:/var/log/nginx/
    links:
      - php

volumes:
  projectsqldata:
    driver: "local"